server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ $uri/index.html $uri.html =404;
  }
  error_page 404 /404.html;

  location /_next/static/ { expires 1y; add_header Cache-Control "public, immutable"; }

  location ~* \.(webp|mp4|jpg|jpeg|png|svg|woff2)$ { expires 30d; add_header Cache-Control "public"; }

  location = /404.html { internal; }
  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  add_header X-Content-Type-Options nosniff;
  add_header Referrer-Policy same-origin;
}
